Blosc/python-blosc

setup.py
It says BSD but the 'lisence' in 'setup' and the file itself are MIT.
=> fix trove classifier

README.rst
=> remove instructions about using the subtree-merge script

blosc/test.py
Hopefully there will never be a codec named 'foo'.
=> check that an invalid cname is caught

blosc/test.py
Currently when tests fail the result is printed on stdout, but it is hard for the caller to know that it failed. Fail verbosely instead.
=> propagate return value from failed tests

RELEASE_NOTES.rst, blosc/blosc_extension.c, blosc/test.py, blosc/toplevel.py, doc/tutorial.rst
Here goes the other half. String and unicode excluded, since they can not be
encoded reliably from compressed data anyway.
=> Decompress from a bytes-like object

RELEASE_NOTES.rst, blosc/blosc_extension.c, blosc/test.py
Just a continuation of #103, here we check only the memory of the current process. Way more robust.
I will let this fail in travis as a proof of concept, then refix the leak, update release notes and we will be ready to go.
=> [MRG] Better memory leak tests

blosc/test.py
ERROR: test_pack_array_exceptions (blosc.test.TestCodec)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/builddir/build/BUILDROOT/python-blosc-1.2.8-2.fc24.i386/usr/lib/python2.7/site-packages/blosc/test.py", line 195, in test_pack_array_exceptions
strides=(8, 0))[0]
File "/usr/lib/python2.7/site-packages/numpy/lib/stride_tricks.py", line 48, in as_strided
array = np.asarray(DummyArray(interface, base=x))
File "/usr/lib/python2.7/site-packages/numpy/core/numeric.py", line 482, in asarray
return array(a, dtype, copy=False, order=order)
TypeError: 'float' object cannot be interpreted as an index
=> tests: fix error with new numpy

blosc/blosc_extension.c, blosc/test.py, blosc/toplevel.py
To make it easier to decompress data into a mutable array without
copying there is a new flag 'as_bytearray' to the decompress
function. This will make decompress return a mutable array of bytes
instead of an immutable collection.
See https://github.com/pydata/pandas/pull/12359 for context on the use case.
About the implementation: I tried having a branch that set two function pointers, one for `from_string_and_size` and the other for `as_string` but that showed worse performance than just using CPP to specialize the two branches. If the you think that the slight performance increase is not worth the code complexity I can repush a change without using CPP for the two branches.
=> Add as_bytearray=False flag to decompress.

setup.py
This was motivated by the fact that [caniusepython3](https://github.com/brettcannon/caniusepython3) doesn't show that blosc supports Python3.
=> Added Python versions for PyPI

.gitignore, README.rst, doc/install.rst, setup.py
Makes use of the `setuptools` build_clib command to separate the codec builds, and thereby prevent namespace collisions and allows for different `cflags` among codecs.  Unfortunately `setuptools` cannot support different compilers for Snappy so the Linux problems for that codec are still present.
=> Separate compilation of codecs

cpuinfo.py
In long running systems, the initial dmesg entries with the CPU info often get wiped out. This information is still saved in the dmesg.boot file (this is just dmesg shortly after boot). This change will get the cpu info script to check the dmesg.boot file as well.
=> Updated cpuinfo.py so that it can use the saved dmesg.boot informatio

cpuinfo.py, setup.py
Cpuinfo.py didn't check for "None\n" which is the result of `print(actual_get_cpu_info_from_cpuid())` on at least this aarch64 platform.
Rest of the fixes should be pretty readily apparent.
Cheers!
=> fixes for building via setup.py on aarch64

blosc/toplevel.py
The doctests for the blocksize -- specifically setting it to 512 -- causes a
random side-effect much later in the test-suite. The fix here is to simply
reset the blocksize to 0 (the default value, meaning an appropriate size will
be selected automaticall) afterwards. As the notes say, 'for expert users
only'.
Fixes #139
=> reset blocksize to default after fidgiting it in doctest

setup.py
Passing `cflags` around as a string instead of list appears to work on Python 2.7 but on 3.6, `setuptools` fails with the error:
$ export INCLUDE_SNAPPY=1
$ python3.6 setup.py build_clib
...
TypeError: can only concatenate list (not "str") to list
This fix makes it build on both 2.7 and 3.6 alike.
=> setup.py: Fix INCLUDE_SNAPPY=1 handling on 3.6

setup.py
Use env vars to switch off SSE and AVX2 cpu detection.
=> Fix #146 Configurable SSE2 and AVX2 cpu detection

blosc/blosc_extension.c
Apparently, this was forgotten for Python3 and actually raising an exception from within c-blosc probably never really worked in Python3.
=> initialize BloscError in Python3 too

blosc/toplevel.py
With https://github.com/Blosc/python-blosc/pull/149/files the `import numpy` statement was added to `toplevel.py`. However this caused issues as outlined in #158 . The resolution is to move the import to the latest point possible. This way, you can use python-blosc without numpy UNLESS you use the `unpack_array` function. The assumption is, that if you are using this, you will have numpy installed anyway. This fixes the previous behaviour and respects the existing interface that numpy isn't a strict dependency of python-blosc.
=> move numpy import into unpack_array

.travis.yml, README.rst, blosc/test.py, doc/install.rst, setup.py
Numpy no longer supports 3.3, so neither should we.
=> Remove support for Python 3.3

setup.py
The license listing is broken on:
https://pypi.org/project/blosc/
This should fix that.
=> fix license listing in setup.py

setup.py
Here's a preliminary proposal fix for #193, where older compilers on newer CPU's would fail to build.
Implementation notes:
- You have to intercept `build_ext` to actually know what compiler is going to be used, anything else is just looking up the 'default' compiler
- Adds an extra flag property to a custom `Extension` subclass that passes the AVX2 flags through to the builder. I didn't want to move the actual extension definitions into the builder class because I felt it might be confusing to have them all over the place. But let me know if you'd prefer (possibly slightly simpler way) that over this method.
I've done some testing but not exhaustively on every platform yet, but wanted to check the approach was acceptable first.
=> Check if the compiler also supports AVX2

MANIFEST.in
The 1.8.0 package on PyPi could not be installed, with the following
error:
gcc -pthread -fno-strict-aliasing -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DHAVE_LZ4=1 -DHAVE_ZLIB=1 -DHAVE_ZSTD=1 -Ic-blosc/blosc -Ic-blosc/internal-complibs/zstd-1.3.8 -Ic-blosc/internal-complibs/snappy-1.1.1 -Ic-blosc/internal-complibs/lz4-1.8.3 -Ic-blosc/internal-complibs/zlib-1.2.8 -Ic-blosc/internal-complibs/lz4-1.8.3 -Ic-blosc/internal-complibs/zstd-1.3.8/common -Ic-blosc/internal-complibs/zstd-1.3.8 -I/opt/python/2.7.14/include/python2.7 -c c-blosc/blosc/blosclz.c -o build/temp.linux-x86_64-2.7/c-blosc/blosc/blosclz.o -DSHUFFLE_SSE2_ENABLED -msse2
c-blosc/blosc/blosclz.c:453:28: fatal error: blosclz_impl.inc: No …
=> include *.inc files too

blosc/toplevel.py
The function was removed in https://bugs.python.org/issue1322
and cannot be used in python3.8.
There are replacements outside of the stdlib, but it doesn't seem
worth it it add a dependency on another module. Instead, a simple
parser for os-release is implemented. os-release is present on all
distros from the last few years and PRETTY_NAME gives a reliable
display name of the distro without any heuristics.
=> Read os-release instead of using platform.linux_distribution()

bench/compare-pack-ptr.py, bench/compress_ptr.py, bench/threadpool.py
Page faults are actually stopping most modern computers from copying fast enough. This was at the heart of a recent discussion 
https://github.com/numpy/numpy/issues/11919
Before this patch:
```
Creating NumPy arrays with 10**8 int64/float64 elements:
compress_ptr.py:29: DeprecationWarning: This function is deprecated. Please call randint(0, 1000 + 1) instead
(np.random.random_integers(0, 1000, N), "the random distribution")
*** ctypes.memmove() *** Time for memcpy():	0.357 s	(2.09 GB/s)
```
After this patch
```
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Creating NumPy arrays with 10**8 int64/float64 elements:
compress_ptr.py:29: DeprecationWarning: This function is deprecated. Please call randint(0, 1000 + 1) instead
(np.random.random_integers(0, 1000, …
```
=> Page fault before the numpy benchmark

MANIFEST.in
pip install fails right now because pip cannot find the skbuild module. This happens because the pyproject.toml file is not included in the source distribution.
=> Fix: pip installation; add pyproject.toml to MANIFEST.in

doc/tutorial.rst
Added a suggestion to make use of the zero-copy functions (compress_ptr, decompress_ptr) with non-numpy objects.
=> Added info and example to docs for compress_ptr

setup.py
If `cpuinfo` fails to import, then `cpu_info` is set to `None` at the top of `setup.py`.  But in the `sse2` check, `cpu_info` is accessed without first checking if it is `None`, causing the pip build to fail.
This fix errs on the conservative side, assuming that we do not want to build SSE2 if `cpuinfo` could not be imported.  It's possible a similar change is needed on the next line for AVX2, but I wasn't sure why there was no `'avx2' not in cpu_info['flags']` condition there in the first place.
=> Fix pip install failure from accessing cpu_info when it is None

blosc/toplevel.py, cpuinfo.py
=> Fix DeprecationWarning due to invalid escape sequence and use array.tobytes for Python 3.9.

blosc/toplevel.py
Very minor fix to `decompress_ptr()` docstring.
=> Fix docstring for decompress_ptr

blosc/blosc_extension.c, blosc/test.py, blosc/toplevel.py
`decompress()` and `decompress_ptr()` currently require the compressed input to be a Python `bytes` object.  `bytes` objects are nice because they're immutable, but this comes at the cost of copying the data when constructing the `bytes`.  So, in Blosc, if you have compressed data in a `bytesarray`, or Numpy array, there's no way to decompress the data without incurring this cost.  Since Blosc decompression can be nearly as fast as a `memcpy()`, this performance hit is noticeable.
This PR changes `decompress()` and `decompress_ptr()` to accept bytes-like input.  Actually, at the CPython level, `decompress()` already allowed bytes-like input, but this was disallowed by the Python wrapper, so I just made that check a little more permissive.
I think this PR is a strict superset of the old …
=> Allow zero-copy decompression by allowing bytes-like input

MANIFEST.in
The file `blosc/c-blosc/README.md` is missing in the sdist `blosc-1.10.0.tar.gz` on PyPI. Building from source fails with the following error (at least on my Windows system):
```
CMake Error at D:/Programs/CMake/share/cmake-3.18/Modules/CPack.cmake:561 (message):
CPack package description file:
"D:/Build/blosc/blosc-1.10.0/blosc/c-blosc/README.md" could not be found.
Call Stack (most recent call first):
D:/Programs/CMake/share/cmake-3.18/Modules/CPack.cmake:565 (cpack_check_file_exists)
blosc/c-blosc/CMakeLists.txt:373 (include)
-- Performing Test Weak Link MODULE -> SHARED (gnu_ld_ignore) - Failed
-- Performing Test Weak Link MODULE -> SHARED (osx_dynamic_lookup) - Failed
-- Performing Test Weak Link MODULE -> SHARED (no_flag) - Failed
_modinit_prefix:PyInit_
-- Configuring incomplete, …
```
=> Fix build error: blosc/c-blosc/README.md could not be found

setup.py
This might resolve an issue where this does not properly write a file when running on PyPy, due to the assumption that the garbage collector will run every line, which is not true on PyPy. It is also more correct usage of the Python language. See https://github.com/joerick/cibuildwheel/issues/533 and https://foss.heptapod.net/pypy/pypy/-/issues/3382 
If you run CPython with warnings on, it will spit out warnings when it sees this, too, by the way:
```bash
$ echo "open('README.md').read()" > tmp.py
$ python3 -Wd tmp.py
```
```
tmp.py:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='README.md' mode='r' encoding='UTF-8'>
open("README.md").read()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```
=> fix: try to fix error on PyPy

.github/workflows/build.yml, .github/workflows/cibuildwheels.yml
Added aarch64 wheel build support.
Related to https://github.com/Blosc/python-blosc/issues/249, @oscargm98 Could you please review this PR?
=> Add aarch64 wheel build support

blosc/test.py
https://deepsource.io/gh/DimitriPapadopoulos/python-blosc/issue/PYL-R0205/occurrences
> The class is inheriting from `object`, which is implicit under Python 3, hence can be safely removed from bases.
=> Useless inheritance from `object`

blosc/__init__.py
https://deepsource.io/gh/DimitriPapadopoulos/python-blosc/issue/PTC-W0041/occurrences
> It is unnecessary to use an _if_ statement to check the minimum of two values and then assign the value to a name. You can use the `min` built-in do do this. It is straightforward and more readable.
=> Use `min` builtin

blosc/__init__.py
https://deepsource.io/gh/DimitriPapadopoulos/python-blosc/issue/PTC-W0015/occurrences
> It is unnecessary to use `list`, `set`, `dict` around a generator expression to get an object of that type since there are comprehensions for these types.
=> Unnecessary generator

blosc/toplevel.py
https://deepsource.io/gh/DimitriPapadopoulos/python-blosc/issue/FLK-E722/occurrences
> Using `except` without a specific exception can be error prone.
See [PEP 8](https://www.python.org/dev/peps/pep-0008/#programming-recommendations):
> When catching exceptions, mention specific exceptions whenever possible instead of using a bare `except:` clause:
> ```
> try:
>     import platform_specific_module
> except ImportError:
>     platform_specific_module = None
> ```
> A bare `except:` clause will catch SystemExit and KeyboardInterrupt exceptions, making it harder to interrupt a program with Control-C, and can disguise other problems. If you want to catch all exceptions that signal program errors, use `except Exception:` (bare except is equivalent to `except …
=> Do not use bare `except`

bench/compress_ptr.py
https://deepsource.io/gh/DimitriPapadopoulos/python-blosc/issue/PYL-W0622/occurrences
> Defining a local variable or function with the same name as a built-in object makes the built-in object unusable within the current scope and makes the code prone to bugs.
Not to mention that my editor would highlight these occurrences of `filter` as a built-in function, which is disturbing.
=> Re-definition of builtin function

setup.py
We keep the last definition, the one that was actually used, shadowing the first definition.
File `README.rst` is an ASCII file, so `encoding='utf-8'` is not really required. If it becomes an issue someday, if non-ASCII characters are added to `README.rst`, you may add the `encoding='utf-8'` keyword argument.
From https://docs.python.org/3.7/library/functions.html#open:
> _encoding_ is the name of the encoding used to decode or encode the file. This should only be used in text mode. The default encoding is platform dependent (whatever [`locale.getpreferredencoding()`](https://docs.python.org/3.7/library/locale.html#locale.getpreferredencoding) returns), but any [text encoding](https://docs.python.org/3.7/glossary.html#term-text-encoding) supported by Python can be used. See the …
=> Variable `long_description` defined multiple times

blosc/test.py, blosc/toplevel.py
Fixes #270.
https://iq-inc.com/importerror-attempted-relative-import/
=> Fix error in tests introduced by #270

setup.py
I have copied the relevant lines from the [setup.py](https://github.com/pypa/sampleproject/blob/main/setup.py) file in the [PyPA sample project](https://github.com/pypa/sampleproject), as suggested in the [packaging](https://packaging.python.org) module documentation:
https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#setup-py
The current documentation states that python-blosc is compatible with Python 3.7 to 3.9:
https://github.com/Blosc/python-blosc/blob/7d40da5f6183ee136988628f7da49f721307a281/setup.py#L66-L69
From there, I have chosen:
1. to enforce Python >=3.7 instead of >=3.6,
2. to add Python 3.10 to the documentation.
Fixes #268.
=> Enforce the Python version the proper way

.github/workflows/build.yml, README.rst, blosc/test.py, blosc/toplevel.py, doc/install.rst
This reverts commit f9b77b9 Revert "Fix error in tests introduced by #270 (#277)"
=>  fix incorrect import of blosc._version

README.rst
Found using `linkchecker https://www.blosc.org/python-blosc/python-blosc.html`
I have removed:
```
A copy of all licenses can be found in `LICENSES/ <LICENSES/>`_.
```
Indeed `python-blosc` has no **`LICENSES`** subdirectory - only `c-blosc` and `c-blosc2` do.
Should we link to https://github.com/Blosc/community/blob/master/code_of_conduct.md or https://github.com/Blosc/c-blosc2/blob/main/code_of_conduct.md?
=> Fix broken links

.github/workflows/build.yml
This shows clearly with '3.10' which is different from '3.1'.
=> python-version should be a string, not a float

blosc/toplevel.py
This is flagged as a security issue by code analysis tools such as DeepSource.io:
>	Spawning of a subprocess using a command shell is dangerous as
>	it is vulnerable to various shell injection attacks. Great care
>	should be taken to sanitize all input in order to mitigate this
>	risk. Calls of this type are identified by the use of certain
>	commands which are known to use shells.
>	[...]
>	It is recommended to use functions that don't spawn a shell.
>	If you must use them, use `shlex.quote` to sanitize the input
>	by changing it to the shell-escaped version.
See:
https://docs.python.org/2/library/subprocess.html#replacing-os-popen-os-popen2-os-popen3
We do not necessarily have a security issue in this specific case, but why start a shell any way?
**Note:** `os.popen2` has been …
=> Avoid starting a process with shell intervention

blosc/toplevel.py
* `os.popen2` → `subprocess.run`
* `cPickle` → `pickle`
=> Remove more deprecated Python 2 stuff

.github/workflows/build.yml, .github/workflows/cibuildwheels.yml, README.rst, setup.py
Because NumPy is a dependency, follow drop schedule of NEP-29:
https://numpy.org/neps/nep-0029-deprecation_policy.html#drop-schedule
=> Drop Python 3.7, minimal version is now 3.8

blosc/toplevel.py
I do not expect `sysctl -n hw.ncpu` to fail, but you never know.
Also use exclusive if because:
* function `os.sysconf` is available on Unix only:
https://docs.python.org/3/library/os.html#os.sysconf
* environment variable `NUMBER_OF_PROCESSORS` is set on Windows only
=> Handle errors gracefully

LICENSE.txt
As in https://github.com/Blosc/c-blosc2/pull/472.
=> Variant for the © symbol: (C) → (c)

blosc/toplevel.py
* Replace deprecated `np.alltrue()` with `np.all()` (available since NumPy 1.7.0).
* Cast NumPy boolean to `bool()`, to ensure doctests pass both with NumPy 2 (using `np.True_`) and NumPy 1 (using plain `True`).
Fixes #327
=> Fix test failures with NumPy 2

MANIFEST.in
Issue #325 describes an issue trying to build with Python 3.12.  The root cause is suggested by these error messages:
```
/usr/bin/ld: blosc/c-blosc/blosc/CMakeFiles/blosc_shared.dir//internal-complibs/zstd-1.5.2/decompress/huf_decompress.c.o: in function HUF_decompress4X1_usingDTable_internal_bmi2_asm': huf_decompress.c:(.text+0x2c2b): undefined reference to HUF_decompress4X1_usingDTable_internal_bmi2_asm_loop'
/usr/bin/ld: blosc/c-blosc/blosc/CMakeFiles/blosc_shared.dir//internal-complibs/zstd-1.5.2/decompress/huf_decompress.c.o: in function HUF_decompress4X2_usingDTable_internal_bmi2_asm': huf_decompress.c:(.text+0x6a58): undefined reference to HUF_decompress4X2_usingDTable_internal_bmi2_asm_loop'
/usr/bin/ld: blosc/c-blosc/blosc/libblosc.so.1.21.3: hidden symbol …
```
=> Fixes #325: Include Assembly Code in Manifest

.github/workflows/build.yml, .github/workflows/cibuildwheels.yml, setup.py
This adds support for Python 3.13, which was released a little while ago. I hope it's helpful - I'm happy to try and fix any issues found, or make any other changes needed.
The motivation here is to have wheels for Python 3.13 available.
=> Add support for Python 3.13
