setup.py
Mostly just noqa because the setup kwargs are all red.
=> pep8 the setup.py a little

README.rst
=> adding talk and slides

.travis.yml, blosc/test.py, setup.py
=> Numpy Test Dependency

blosc/test.py
No need to depend on 'mock' just yet.
=> pretend like we have a huge object

README.rst
Appveyor badge fix image + target
You could check it here https://github.com/FrancescElies/python-blosc/tree/appveyor_v3
=> Appveyor v3 - fix

.gitignore, .travis.yml, RELEASE_NOTES.rst, blosc/blosc_extension.c, blosc/test.py
This should be ready to merge.  But perhaps we miss a test. I wonder if there is a good way to test for memory leaks.
closes #102
=> [MRG] release buffer

blosc/blosc_extension.c
Also makes some char* const char*.
=> BUG: fix ref some counts in blosc_extension.

blosc/__init__.py, blosc/blosc_extension.c, blosc/test.py, blosc/toplevel.py
Implemented basic methods extracting information about the blocksize.
=> Blocksize info support

blosc/toplevel.py
will go green after #140 is merged.
=> prune trailing whitespace

.travis.yml
will go green after #140 is merged.
=> travis py36

.travis.yml, setup.py
Start testing on Python 2.7 too.
=> Travis py 37

ANNOUNCE.rst, LICENSES/PYTHON-BLOSC.txt, README.rst, RELEASE_NOTES.rst, doc/conf.py
@FrancescAlted @robbmcleod @FrancescElies I prepped a changelog for version 1.6.0 - please check the attributions and wording and let me know if I have missed anything.
=> Prep 1.6.0

.travis.yml, README.rst, blosc/test.py, doc/install.rst, setup.py
Does what it says, hope I found all occurrences.
=> Remove python 26 support

cpuinfo.py
Copy cpuinfo.py from:
https://github.com/workhorsy/py-cpuinfo/blob/4e4e5ca9e9612507d7c70a79fadcfb17cd4d4f2b/cpuinfo/cpuinfo.py
=> upgrade to vendored cpuinfo.py v4.0.0

setup.py
=> Protect entire `setup.py` from multiprocessing on Win

blosc/blosc_extension.c
just some whitespace issues my vim highlighted.
=> fix whitespace

doc/install.rst
Totally forgot about this, might be time to revamp the installation instructions again.
=> mention conda install in sphinx docs

azure-pipelines.yml
=> Build Windows Python 3.8 wheel

doc/tutorial.rst
just fixes a couple spelling typos in the docs tutorial
=> fixes spelling errors

setup.py
=> Deactivate SSE2 and AVX2 if a CPU has no flags

bench/compare-pack-ptr.py, bench/compress_ptr.py, bench/threadpool.py, blosc/c-blosc/bench/plot-speeds.py, blosc/c-blosc/tests/check_symbols.py, blosc/test.py, blosc/toplevel.py, setup.py
Get rid of code specific to Python 2.
=> Python 2 is not supported any more

README.rst, doc/install.rst
=> Deprecate nose

.lgtm.yml
Add a configuration file for the LGTM.com static code analysis tool. It requires no CI integration, as the LGTM.com tool continuously scans the python-blosc GitHub repository for security and/or code vulnerabilities. You can find the alerts here:
https://lgtm.com/projects/g/Blosc/python-blosc/
The YAML configuration file for the LGTM static analysis tool can be either `lgtm.yml` or `.lgtm.yml`:
https://lgtm.com/help/lgtm/lgtm.yml-configuration-file
=> Add LGTM.com configuration file

cpuinfo.py
Bump the vendored `cpuinfo.py` file from [8.0.0](https://github.com/workhorsy/py-cpuinfo/releases/tag/v8.0.0) to [9.0.0](https://github.com/workhorsy/py-cpuinfo/releases/tag/v9.0.0).
=> cpuinfo 8.0.0 → 9.0.0

ANNOUNCE.rst, README.rst, blosc/toplevel.py, doc/intro.rst, doc/tutorial.rst, setup.py
* Update links in the process.
=> http:// → https://

bench/compare-pack-ptr.py, bench/compress_ptr.py
What are you exactly trying to assert here? Whether a tuple is not empty? Whether all iterables are True?
The parentheses can probably be removed.
=> Assert is a simple statement: no perentheses!
